# .github/workflows/ci.yml

name: AdonisJS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Inicia un servicio de PostgreSQL
    services:
      # Le pedimos a github que inicie un contendor docker con la imagen de postgres
      postgres:
        image: postgres:14.1-alpine
        # Configuramos el nombre las credenciales de la BD en el contenedor
        env:
          POSTGRES_DB: adonis_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        # Mapeando el puerto del contenedor
        ports:
          - 5432:5432
        # Opción para asegurar que el servicio esté listo antes de continuar
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm run test
        env:
          # Usando el secret de entorno creado en github (Settings > Secrets and variables > actions)
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: password
          DB_DATABASE: adonis_test
          # Variables adicionales
          TZ: UTC
          SESSION_DRIVER: memory
          HOST: localhost
          LOG_LEVEL: info
          PORT: 3333